# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "55855c3f6a7ed867befb26fc60cd470d"
name = "Feedcompliant"
application_url = "https://feedcompliant.com"
embedded = false

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_legal_policies,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://feedcompliant.com/api/shopify/callback" ]

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://feedcompliant.com/api/webhooks/shopify"
