// Compares two stored audit reports and returns which issues are new, which
// are resolved, and how many are unchanged. The email module (session 2)
// consumes the persisted result; nothing here sends anything.
//
// Issue identity must be STABLE across runs. The French text of problem/fix is
// generated by Claude and can vary from one run to the next, so it is never
// part of the key. We key on the structural coordinates of an issue instead:
// its area, the concrete Shopify target when a patch exists (a verbatim GID or
// policy code), otherwise the product title, plus the patched field. This is
// the closest thing to a stable code the report format offers.

type Patch = {
  fixType?: string | null;
  field?: string | null;
  targetId?: string | null;
};

export type AuditIssue = {
  area?: string | null;
  product?: string | null;
  severity?: string | null;
  source?: string | null;
  problem?: string | null;
  fix?: string | null;
  patch?: Patch | null;
};

export type AuditReport = {
  issues?: AuditIssue[] | null;
} | null | undefined;

export type AuditDiff = {
  newIssues: AuditIssue[];
  resolvedIssues: AuditIssue[];
  unchangedCount: number;
};

function norm(value: unknown): string {
  return typeof value === "string" ? value.trim().toLowerCase() : "";
}

// Stable identity for one issue. Prefers the patch target (a verbatim Shopify
// GID or policy code) as the anchor; falls back to the product title, then to
// the problem text only as a last resort so two genuinely distinct store-wide
// issues in the same area are not collapsed into one.
function issueKey(issue: AuditIssue): string {
  const area = norm(issue.area) || "unknown";
  const patch = issue.patch ?? null;
  const target =
    norm(patch?.targetId) ||
    norm(issue.product) ||
    norm(patch?.fixType) ||
    norm(issue.problem);
  const field = norm(patch?.field);
  return `${area}|${target}|${field}`;
}

function issuesOf(report: AuditReport): AuditIssue[] {
  const issues = report?.issues;
  return Array.isArray(issues) ? issues : [];
}

export function computeAuditDiff(
  previousReport: AuditReport,
  newReport: AuditReport,
): AuditDiff {
  const previousIssues = issuesOf(previousReport);
  const newReportIssues = issuesOf(newReport);

  const previousKeys = new Set(previousIssues.map(issueKey));
  const newKeys = new Set(newReportIssues.map(issueKey));

  const newIssues = newReportIssues.filter(
    (issue) => !previousKeys.has(issueKey(issue)),
  );
  const resolvedIssues = previousIssues.filter(
    (issue) => !newKeys.has(issueKey(issue)),
  );
  const unchangedCount = newReportIssues.filter((issue) =>
    previousKeys.has(issueKey(issue)),
  ).length;

  return { newIssues, resolvedIssues, unchangedCount };
}
